#invalid_nan - input = dummyData_invalid_nan.csv - ['2', '5']
#invalid_nan - input = dummyData_invalid_nan_source - ['6', '7', '10', '16', '18', '19', '49', '53', '63']
#duplicate_wdpa_pid - ['2','3','7','8']
#area_invalid_marine - ['4', '7', '10']
#area_invalid_too_large_gis - ['3','8']
#area_invalid_too_large_rep - ['5','9','10']
#area_invalid_too_large_gis_m - ['1','2']
#area_invalid_too_large_rep_m - ['4','7']
#area_invalid_gis_area - ['5','10']
#area_invalid_rep_m_area_marine12 - ['3','6','9']
#area_invalid_gis_m_area_marine12 - ['3','8','10']
#invalid_no_take_no_tk_area_rep_m_area - ['1','4']
#invalid_int_crit_desig_eng_other - ['1','5','8']
#invalid_desig_eng_iucn_cat_other - ['5','7','9']
#inconsistent_fields_same_wdpaid - no single test
#inconsistent_name_same_wdpaid - ['3','4','5','7','8','9','10']
#inconsistent_orig_name_same_wdpaid - ['1','2','3','4','7','8','9','10']
#inconsistent_desig_same_wdpaid - ['3','4','5','8','9','10']
#inconsistent_desig_eng_same_wdpaid - ['3','4','5','8','9','10']
#inconsistent_desig_type_same_wdpaid - ['1','2','3','9','10']
#inconsistent_iucn_cat_same_wdpaid - ['4','5','6', '8','9','10']
#inconsistent_int_crit_same_wdpaid - ['3','4','7','8']
#inconsistent_no_take_same_wdpaid - ['1','2','3']
#inconsistent_status_same_wdpaid - ['3','4','5']
#inconsistent_status_yr_same_wdpaid - ['1','2']
#inconsistent_gov_type_same_wdpaid - ['2','3']
#inconsistent_own_type_same_wdpaid - ['5','6','7']
#inconsistent_mang_auth_same_wdpaid - ['2','3','6','7']
#inconsistent_mang_plan_same_wdpaid - ['7','8','9','10']
#inconsistent_verif_same_wdpaid - ['7','8']
#inconsistent_metadataid_same_wdpaid - ['5','6','7','8']
#inconsistent_sub_loc_same_wdpaid - ['2','3','9','10']
#inconsistent_parent_iso3_same_wdpaid - ['2','3','8','9',]
#inconsistent_iso3_same_wdpaid - ['8','9','10']
#invalid_value_in_field - no single test
#invalid_pa_def - ['1','7','10']
#invalid_desig_eng_international - ['2','3','8']
#invalid_desig_type_international - ['5','8']
#invalid_desig_eng_regional =- ['1','3','6']
#invalid_desig_type_regional - ['6','8']
#invalid_int_crit_desig_eng_ramsar_whs - ['5','9','10']
#invalid_desig_type - ['4','6','9']
#invalid_iucn_cat - ['4','7','10']
#invalid_iucn_cat_unesco_whs - ['7','10']
#invalid_marine - ['5','7','10']
#invalid_no_take_marine0 - ['1','3','6']
#invalid_no_take_marine12 - ['3','6','8']
#invalid_no_tk_area_marine - ['2','4','8']
#invalid_no_tk_area_no_take - ['2','4','8','10']
#invalid_status - ['1','5','7','9']
#invalid_status_yr - ['1','4','5']
#invalid_gov_type - ['1','3','6']
#invalid_own_type - ['3','7']
#invalid_verif - ['3','4','7']
#invalid_parent_iso3 - ['1','4','9']
#invalid_iso3 - ['1','2','3']
#invalid_status_desig_type - ['1','4','7','9']
#area_invalid_size - no single test
#area_invalid_no_tk_area_rep_m_area - ['3','5','7']
#area_invalid_no_tk_area_gis_m_area - ['1','2','5']
#area_invalid_gis_m_area_gis_area - ['2','5','8']
#area_invalid_rep_m_area_rep_area - ['2','7','9']
# forbidden_character - no single test
#forbidden_character_name - ['1','2','5','8','9','10']
#forbidden_character_orig_name - ['2','4','7','9']
#forbidden_character_desig - ['2','4','7','10']
#forbidden_character_desig_eng - ['1','3','6']
#forbidden_character_mang_auth - ['1','4','7']
#forbidden_character_mang_plan - ['1','5','8','9']
#forbidden_character_sub_loc - ['2','3','4','7']
#invalid_metadataid_not_in_source_table - ['1','2','3']
#invalid_metadataid_not_in_wdpa - ['6','7','10','13','16','18','19','49','53']